### ISSUE TITLE
Allow for specifying router's database credentials at instantiation time

### ISSUE THREAD

**Issue by jugglinmike** [wfmu/ae-utils#13]
Instead of relying on a global constant, the Router should be instantiated with database credentials specified via formal parameters. This will make consuming the router easier for applications (especially during testing).

**Comment by carldanley** [comment]
I wish there were a better way to pass around an instance of an application object that would contain these credentials (or its own configuration) rather than forcing the router to do it; seems weird that the router needs to know about the database.

**Comment by carldanley** [comment]
Though, if this is a quick win, we can just document a better approach for when we have time versus actually implementing it now?

**Comment by MattSurabian** [comment]
This has been resolved
