### ISSUE TITLE
Extend `defaultFunction` to optionally accept parameters

### ISSUE THREAD

**Issue by jugglinmike** [wfmu/ae-utils#27]
Models should be able to declare attributes whose `defaultFunctions` are invoked with specific attributes, e.g.

```php
class MyModel extends BaseModel {
  protected $_db_schema = array(
    'myAttr' => array(
      'type' => 'int',
      'defaultFunction' => array('Model::myAttrDefaultFunction', array('param1', 'param2'))
    )
  );
  static public function myAttrDefaultFunction($a, $b) {
    // etc.
  }
}
```

Implementation note: this will likely require the use of [the `call_user_func_array` built-in function](https://secure.php.net/manual/en/function.call-user-func-array.php)

**Comment by MattSurabian** [comment]
Resolved
